config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorite_images, only: [:create, :destroy, :show]
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_image.rb
class FavoriteImage < ApplicationRecord
    belongs_to :picture
    belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :favorite_images
    has_many :favorited_by, through: :favorite_images, source: :user # liste des utilisateurs ayant aimé cette image

end

app/models/user.rb
class User < ApplicationRecord
    before_validation { email.downcase! }
    validates :password, presence: true, length: { minimum: 4 }
    validates :name, presence: true 
    validates :email, presence: true 
    has_secure_password
    has_many :pictures
    has_many :favorite_images
    has_many :favorites_images, through: :favorite_images, source: :picture # les images likés par l'utilisateur

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required
    def login_required 
        redirect_to new_session_path unless current_user
    end
    
end

app/controllers/favorite_images_controller.rb
class FavoriteImagesController < ApplicationController
    def show
      @favorites = current_user.favorite_images.all
    end 
    def create
      favorite = current_user.favorite_images.create(picture_id: params[:picture_id])
      redirect_to pictures_path, notice: "#{favorite.picture.user.name}'S Post has been added to favorites"
    end
    def destroy
      favorite = current_user.favorite_images.find_by(id: params[:id]).destroy
      redirect_to pictures_path, notice: "#{favorite.picture.user.name}Unblogged Mr.'s Post"
    end
  end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action:set_pic, only: [:show, :update, :edit, :destroy]

    def new
        @picture = Picture.new
    end
    def show 
        @favorite = current_user.favorite_images.find_by(picture_id: @picture.id)
    end 
    def edit
    end
    def update 
        if @picture.update(pic_params)
            redirect_to pictures_path, notice: "Mise à jour effectuée !"
          else
            render :edit
        end
    end
    def index
        @pictures = Picture.all
    end
    def create 
        @picture = current_user.pictures.build(pic_params)
        if params[:back]
            render :new
        else
            if @picture.save 
                redirect_to new_picture_path
            else
                render :new
            end
        end
    end
    def destroy
        @picture.destroy
        redirect_to pictures_path, notice:"Image supprimée!"
    end
    def confirm 
        @picture = current_user.pictures.build(pic_params)
        render :new if @picture.invalid?
    end
        

    private
    def pic_params
        params.require(:picture).permit(:image, :image_cache)
    end
    def set_pic
        @picture= Picture.find(params[:id])
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create 
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to new_picture_path
    else 
      flash.now[:danger] = " Connexion non acceptée "
      render :new
    end 
  end 
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'logged Out' 
    redirect_to new_session_path
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :login_required, only: [:new, :create]
    def new
        @user = User.new
    end
    def show
        @user = User.find(params[:id])
    end 
    def index 
        @users = User.all 
    end 
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user),notice: "The user has been created"
        else 
            render :new
        end

    end 
    def edit
        @user = User.find(params[:id])
    end
    
    def update
         @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to user_path(@user.id), notice: "I was able to post!"
    
        else
        render :edit
        end
    end
    
    def set_user
        @user = user.find(params[:id])
    end
    
    def destroy
        @user.destroy
        redirect_to users_path, notice: "I deleted the blog!"
    end


    private 
    def user_params
        params.require(:user).permit(:name, :email, :password , :password_confirmation)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
    def choose_new_or_edit
      if action_name == 'new' || action_name == 'create'
        confirm_pictures_path
      elsif action_name == 'edit'
        picture_path
      end
    end
  end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        current_user ||= User.find_by(id: session[:user_id])
    end 
    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorite_images/show.html.erb
<h1>
<p> Vous avez : <%= @favorites.count %> images dans vos favoris </p>
</h1>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceBookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="page-footer font-small blue pt-4""> 
    <nav class="navbar navbar-expand-sm bg-danger navbar-dark">
      <a class="navbar-brand" href="#">
      <div class="style"><font size="12" color="blue">FACEBOOK CLONE</font></div></a>
      <form class="form-inline my-2 my-lg-0">
        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id), class:"btn btn-primary btn-sm"%>
          <%= link_to "Logout", session_path(current_user.id),class:"btn btn-primary btn-sm", method: :delete %>
        <% else %>
          <%= link_to "Login", new_session_path,class:"btn btn-primary btn-sm" %>
          <%= link_to "SignUp", new_user_path,class:"btn btn-primary btn-sm" %>
        <% end %>
      </form>
    </nav>
  </header>
  <body>
    <div class = container > 
      <% flash.each do |key, value| %> 
        <%= content_tag(:div, value, class: "#{key}") %> 
      <% end %>
      <%= yield %>      
    </div>
  </body>
  <!-- Footer -->
  <footer style="background: blue;" class="page-footer font-small blue pt-4">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://diver.diveintocode.jp/"> Dive Into Code</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaceBookApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class="page-footer font-small blue pt-4"">    
    <nav class="navbar navbar-expand-sm bg-danger navbar-dark">
      <a class="navbar-brand" href="#">
      <div class="style"><font size="12" color="blue">FACEBOOK CLONE</font></div></a>
      <form class="form-inline my-2 my-lg-0">
        <% if logged_in? %>
          <%= link_to "Profile", user_path(current_user.id), class:"btn btn-primary btn-sm"%>
          <%= link_to "Logout", session_path(current_user.id),class:"btn btn-primary btn-sm", method: :delete %>
        <% else %>
          <%= link_to "Login", new_session_path,class:"btn btn-primary btn-sm" %>
          <%= link_to "SignUp", new_user_path,class:"btn btn-primary btn-sm" %>
        <% end %>
      </form>
    </nav>
  </header>
  <body>
    <div class = container > 
      <% flash.each do |key, value| %> 
        <%= content_tag(:div, value, class: "#{key}") %> 
      <% end %>
      <%= yield %>      
    </div>
  </body>
  <!-- Footer -->
  <footer style="background: blue;" class="page-footer font-small blue pt-4">
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://diver.diveintocode.jp/"> Dive Into Code</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</html>

app/views/pictures/_form.html.erb
<div class ="container" >
<%= form_with(model: @picture, local: true,url: choose_new_or_edit) do |form| %>
  
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
  
        <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
    <%= form.label :image %><br>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %> <br>
    <%= form.hidden_field :image_cache %>
    </div>
    <div>
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
    </div>

    <div class="actions">
    <%= form.submit %>
    </div>
    

<% end %>
<div>
  

app/views/pictures/confirm.html.erb
<h3>Confirmation du Post</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  "register" %>
<% end %>
<%= form_with(model: @picture, url: new_picture_path, local: true) do |form| %>
  <%= form.hidden_field :image_cache  %>
  <p>Description:<%= @picture.description %></p>
  <%= form.submit  "Return" ,name: 'back'%>
<% end %>

app/views/pictures/edit.html.erb
<h1> EDITION POUR MISE A JOUR  </h1>
<%= form_with(model: @picture, local: true) do |form| %>
    <% if @picture.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>
  
        <ul>
        <% @picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
    <div class="field">
      <%= form.label :Description %>
      <%= form.text_area :description %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>
  

app/views/pictures/index.html.erb
<h1>LISTE DE TOUS LES POSTS </h1>
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>MBlogs Dive</title>
    <link rel="stylesheet" href="./css/normalize.css">
    <link rel="stylesheet" href="./css/sample.css">
</head>
<body>
<p><%= notice %></p>
<table>
    <tr>
        <th>Image </th>
        <th>Description</th>
        <th>Action 1</th>
        <th>Action 2</th>
        <th>Action 3</th>
    <tr>
    <% @pictures.each do |p| %>
        <tr>
            <td><%= image_tag p.image.url  %></td>
            <td><%= p.description %></td>
            <td><%= link_to 'Details', picture_path(p.id) %></td>  
            <td><%= link_to 'Editer', edit_picture_path(p.id) %></td> 
            <td><%= link_to 'Supprimer', picture_path(p.id), method: :delete, data: { confirm: 'Voulez vous vraiment supprimer cette image ? '} %></td>
        </tr>
    <% end %>
</table>
<br>
</body>
</html>
<%= link_to 'Nouveau Post', new_picture_path %>

app/views/pictures/new.html.erb
<h1>  POSTER UNE IMAGE  </h1>
<%= render 'form',  picture: @picture %>
<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<h1> DETAILS DU POST  </h1>
<p>
  <strong>Image:</strong>
  <%=image_tag @picture.image.url %>
</p>
<p>
  <strong>DESCRIPTION:</strong>
  <%= @picture.description %>
</p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'Remove favorite', favorite_image_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'Favorite', favorite_images_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
  

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/users/index.html.erb
<%= render 'form' %>
<table>
    <tr>
        <th>Login </th>
        <th>Email</th>
        <th>Action 1</th>
        <th>Action 2</th>
        <th>Action 3</th>
    <tr>
    <% @users.each do |p| %>
        <tr>
            <td><%= p.name %></td>
            <td><%= p.email %></td>
            <td><%= link_to 'Details', user_path(p.id) %></td> 
            <td><%= link_to 'Editer', edit_user_path(p.id) %></td> 
            <td><%= link_to 'Supprimer', user_path(p.id), method: :delete, data: { confirm: 'Voulez vous vraiment supprimer cet utilisateur ? '} %></td>
                 
        </tr>
    <% end %>
</table>
<br>
<%= link_to 'Creer un nouvel utilisateur ', new_user_path %>

app/views/users/new.html copy.erb
<%= render 'form' %>
<%= form_with(model: @user, local: true) do |form| %>
  <div class ="container">
    <h1> New User Account  </h1>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :Email  %>
      <%= form.email_field :email %>
    </div>
    <div class="field">
      <%= form.label :Password   %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :Password_Confirmation  %>
      <%= form.password_field :password_confirmation %>
    </div>
    <br>
    <div class="actions">
      <%= form.submit"Créer mon compte" %>
    </div>
  </div>
<% end %>
  

app/views/users/new.html.erb
<%= render 'form' %>
<%= form_with(model: @user, local: true) do |form| %>
  <div class ="container">
    <br>
    <%= form.text_field :name , placeholder: "Enter Your name " %><br>
    <br>
    <%= form.text_field :email, placeholder: "Enter Your Email address" %><br>
    <br>
    <%= form.password_field :password, placeholder: "Enter Your password" %><br>
    <br>
    <%= form.password_field :password_confirmation, placeholder: "Enter Your password" %><br>
    <br>
    <%= form.submit " Create my account" %>
    </div>
  <br><br> 
<% end %>
  

app/views/users/show.html.erb
<h1> Votre Profile </h1>
<p>Login :<%= @user.name %></p>
<p>Email : <%= @user.email %></p>
<%= link_to 'Voir les images ', pictures_path %> | 
<%= link_to 'Mes Favoris ', favorite_image_path(id: current_user.id) %>